Update cp__latest_dispatch.yml

diff --git a/.github/workflows/cp__latest_dispatch.yml b/.github/workflows/cp__latest_dispatch.yml
--- a/.github/workflows/cp__latest_dispatch.yml
+++ b/.github/workflows/cp__latest_dispatch.yml
@@ -49,7 +49,6 @@ jobs:
 
     env: 
       SCRAPED_VERSION: ${{ needs.scrape_fe_version.outputs.scraped_version }}
-      FIXED_HOSTPOLICY_URL: "https://github.com/project-yui/Yui-patch/releases/download/v1.1.3/yui-hostpolicy-win32-x86_64-v1.1.3.dll"
       
     outputs:
       is-compatible-cont: ${{ steps.is-compatible-cont.outputs.is-compatible-cont }}
@@ -71,6 +70,7 @@ jobs:
           } else {
               echo "IS_COMPATIBLE_CONT=false" | Out-File -Append -FilePath $env:GITHUB_ENV
           }
+        
         shell: pwsh
 
       - name: Set IS_COMPATIBLE_CONT as Output
@@ -104,18 +104,34 @@ jobs:
           }
         shell: pwsh
 
-      - name: Download Yui Fiddler Patch
-        run: |
-          $YuiFiddlerUrl = "https://github.com/project-yui/Yui-patch/releases/download/$env:Yui_RELEASE/$env:YUI_NAME-$env:Yui_FIDDLER_NAME-win32-x86_64-$env:Yui_RELEASE.dll"
-          
-          Write-Host "Downloading Yui Fiddler from: $YuiFiddlerUrl"
-          Invoke-WebRequest -Uri $YuiFiddlerUrl -OutFile "Yui\$env:Yui_FIDDLER_NAME.dll"
-        shell: pwsh
+      - name: Set Yui Release (>= 5.17.0)
+        if: env.IS_COMPATIBLE_CONT == 'true'
+        run: echo "Yui_RELEASE=continuous" | Out-File -Append -FilePath $env:GITHUB_ENV
 
-      - name: Download Fixed HostPolicy
+      - name: Set Yui Release (< 5.17.0) 
+        if: env.IS_COMPATIBLE_CONT == 'false'
+        run: echo "Yui_RELEASE=v1.0.9" | Out-File -Append -FilePath $env:GITHUB_ENV
+        
+      - name: Download Yui Patch
         run: |
-          Write-Host "Downloading Fixed HostPolicy from: $env:FIXED_HOSTPOLICY_URL"
-          Invoke-WebRequest -Uri $env:FIXED_HOSTPOLICY_URL -OutFile "Yui\hostpolicy.dll"
+          try {
+            # Build the download URLs
+            $YuiFiddlerUrl = "https://github.com/project-yui/Yui-patch/releases/download/$env:Yui_RELEASE/$env:YUI_NAME-$env:Yui_FIDDLER_NAME-win32-x86_64-$env:Yui_RELEASE.dll"
+            $YuiHostPolicyUrl = "https://github.com/project-yui/Yui-patch/releases/download/v1.1.3/yui-hostpolicy-win32-x86_64-v1.1.3.dll"
+            
+            # Print the URLs to ensure they're correct
+            Write-Host "Downloading files from $env:Yui_RELEASE"
+            Write-Host "Yui Fiddler URL: $YuiFiddlerUrl"
+            Write-Host "Yui HostPolicy URL: $YuiHostPolicyUrl"
+
+            # Download the files
+            Invoke-WebRequest -Uri $YuiFiddlerUrl -OutFile "Yui\$env:Yui_FIDDLER_NAME.dll"
+            Invoke-WebRequest -Uri $YuiHostPolicyUrl -OutFile "Yui\hostpolicy.dll"
+          }
+          catch {
+            Write-Error "Failed to download the patch files. Error details: $_"
+            exit 1
+          }
         shell: pwsh
       
       - name: Upload Yui folder as an artifact
@@ -124,7 +140,6 @@ jobs:
           name: Yui-patch
           path: Yui/
           if-no-files-found: error
-
 
   download-msojocs-server:
     runs-on: windows-latest
